# Generated by Django 2.1.4 on 2018-12-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_ciudad_url_pagina'),
        ('ubereats', '0002_auto_20181219_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaCiudad',
            fields=[
                ('ciudad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Ciudad')),
                ('url', models.URLField()),
                ('csrftoken', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Pagina por ciudad',
                'verbose_name_plural': 'Paginas por ciudad',
            },
            bases=('main.ciudad',),
        ),
    ]
