# Generated by Django 2.1.4 on 2018-12-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0003_paginaciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('primera', models.BooleanField(default=False)),
                ('offset', models.CharField(blank=True, max_length=15, null=True)),
                ('pageSize', models.CharField(blank=True, max_length=15, null=True)),
                ('request_payload', models.CharField(max_length=1000)),
                ('data', models.TextField(blank=True, null=True)),
                ('pagina_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.PaginaCiudad')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
    ]
