# Generated by Django 2.1.4 on 2018-12-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0008_tienda_direccion_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='HourDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
            },
        ),
        migrations.CreateModel(
            name='ProductoBusqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busquedas', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.DayWeek')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.HourDay')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.Productos')),
            ],
            options={
                'verbose_name': 'Busqueda por producto',
                'verbose_name_plural': 'Busquedas por producto',
            },
        ),
        migrations.CreateModel(
            name='TiendaBusqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busquedas', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.DayWeek')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.HourDay')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.Tienda')),
            ],
            options={
                'verbose_name': 'Busqueda por tienda',
                'verbose_name_plural': 'Busquedas por tienda',
            },
        ),
    ]
