# Generated by Django 2.1.4 on 2018-12-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0010_auto_20181227_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginaciudad',
            name='timezone',
        ),
    ]
