# Generated by Django 2.1.4 on 2018-12-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0012_paginaciudad_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobusqueda',
            name='editado',
        ),
        migrations.RemoveField(
            model_name='tiendabusqueda',
            name='editado',
        ),
        migrations.AddField(
            model_name='tienda',
            name='last_trend',
            field=models.DateField(auto_now=True),
        ),
    ]
