# Generated by Django 2.1.4 on 2018-12-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0013_auto_20181227_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='last_trend',
        ),
    ]
