# Generated by Django 2.1.4 on 2018-12-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0014_remove_tienda_last_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='last_trend',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
