# Generated by Django 2.1.4 on 2019-01-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0016_auto_20181229_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='last_google',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='last_trend',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
