# Generated by Django 2.1.4 on 2019-01-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0017_auto_20190102_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaciudad',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
