# Generated by Django 2.1.4 on 2019-01-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0019_urls_mapeado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ciudad solicitada',
                'verbose_name_plural': 'Ciudades solicitados',
            },
        ),
        migrations.CreateModel(
            name='PaisRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pais solicitado',
                'verbose_name_plural': 'Paises solicitados',
            },
        ),
        migrations.AddField(
            model_name='ciudadrequested',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubereats.PaisRequested'),
        ),
    ]
